name: 'Api-Check'
description: 'Api Check'
inputs:
  repo_name:
    description: 'repo name'
    required: false
    default: ${{github.repository}}
outputs:
  isFail:
    description: "the check is fail or not"
    value: ${{ steps.check-api.outputs.isFail }}
  check_num:
    description: "the check result"
    value: ${{ steps.check-api.outputs.check_num }}
  summary-status:
    description: 'summary status'
    value: ${{ steps.get-summary-result.outputs.summary-status }}
  summary-result:
    description: 'summary result'
    value: ${{ steps.get-summary-result.outputs.summary-result }}

runs:
  using: "composite"
  steps:
    - name: install tools
      shell: bash
      run: |
        sudo apt-get install quilt -y
        sudo apt-get install universal-ctags -y
    - name: download base code
      uses: actions/checkout@v4
      with:
        repository: ${{inputs.repo_name}}
        path: baseCodeDir
    - working-directory: ./baseCodeDir
      shell: bash
      run: |
        if [ -d "debian/patches" ];then
          if [ "`ls -A debian/patches`" != "" ];then
              cp debian/patches . -fr
              quilt push -a || true
          fi
        fi
    - name: download new code
      uses: actions/checkout@v4
      with:
        repository: ${{inputs.repo_name}}
        ref: ${{ github.event.pull_request.head.sha }}
        path: currentCodeDir
    - working-directory: ./currentCodeDir
      shell: bash
      run: |
        if [ -d "debian/patches" ];then
            if [ "`ls -A debian/patches`" != "" ];then
                cp debian/patches . -fr
                quilt push -a  || true
            fi
        fi
    - id: check-api
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/deepin-abigail -c $GITHUB_ACTION_PATH/fastFilesCompare.json | tee api_check.txt
        logMsg1='''
        <details>
          <summary>详情</summary>
        
        ```ruby
        '''
        logMsg2='''
        ``` 
        </details>
        '''
        detailUrl="https://github.com/reviews-team-test/infra-settings/blob/master/services/prow/config/jobs/images/api-check/readme.md"
        logMsgHead="> [!WARNING]\n> [[API接口检查]]($detailUrl)\n- 检测到存在对外接口删除和修改"
        if [ -e 'api_check.txt' ];then
          resultInfoMsg=$(cat api_check.txt)
          check_num=$(cat api_check.txt | grep -c '\[Chg_exprort_fun\|\[Del_export_fun' || true)
          if [ $check_num -gt 0 ];then
            echo "isFail=true" >> $GITHUB_OUTPUT
            echo "check_num=$check_num" >> $GITHUB_OUTPUT
            echo -e "${logMsgHead}${logMsg1}${resultInfoMsg}${logMsg2}" | tee comment.txt
          fi
        fi
    - id: get-summary-result
      if: always()
      shell: bash
      run: |
        summary_status="是"
        if [ "$isFail" == "true" ]; then
            summary-status="否"
        fi
        check_num=$([ "$check_num" == '' ] && echo "0" || echo "$check_num")
        echo "summary-status=$summary_status" >> $GITHUB_OUTPUT
        echo "summary-result=$check_num" >> $GITHUB_OUTPUT
      env:
        isFail: ${{ steps.check-api.outputs.isFail }}
        check_num: ${{ steps.check-api.outputs.check_num }}
